services:
  - type: web
    name: nptel-rag-chatbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_MODEL
        value: gemini-3-flash-preview
      - key: DOCS_DIR
        value: docs
      - key: GDRIVE_FOLDER_URL
        value: https://drive.google.com/drive/folders/1aa9GiBKwqPv8LXCUzXeSrRg2mHxoKFhN?usp=drive_link
      - key: GEMINI_API_KEY
        sync: false
